Owen/accessibility contrast changes
aminohealth/phenotypes pull request #131
Opened 2021-05-21 18:51 UTC by orjames

Accessibility changes related to contrast issues here:
https://airtable.com/tbl5wF3jbscbZt1HU/viwLnwL8sehpah7QC?blocks=hide

Sketch Files Here:
Input boxes:
https://www.sketch.com/s/43c0a41d-18f0-4c8d-aa7e-e8a0ebb85f4a/v/p84nxp/a/zxzW9Ko/#Inspector

Buttons:
https://www.sketch.com/s/43c0a41d-18f0-4c8d-aa7e-e8a0ebb85f4a/a/pj8Kar#Inspector

Radio Buttons and Check Boxes:
https://www.sketch.com/s/43c0a41d-18f0-4c8d-aa7e-e8a0ebb85f4a/a/bgMQrbj

2021-05-25 00:26 UTC, ahmedmodan reviewed
Overall looks really good! thanks for adding those vars and updating to the new styling. One q that I think we should wait on sumul for. But aside from that lgtm

2021-05-25 00:26 UTC, ahmedmodan commented on library/components/button/_button.scss
> +      padding: modular-scale-px(0) modular-scale-px(5) modular-scale-px(1);
I think @sumul said something about ignoring any padding changes?

2021-05-25 00:35 UTC, orjames commented on library/components/button/_button.scss
> +      padding: modular-scale-px(0) modular-scale-px(5) modular-scale-px(1);
Ah. I read that as related to text inputs, but you may be right: https://aminohealth.slack.com/archives/C2JQHTV8F/p1621608051014200

2021-05-25 19:32 UTC, ahmedmodan requested changes

2021-05-25 19:32 UTC, ahmedmodan commented on library/components/button/_button.scss
> +      padding: modular-scale-px(4) modular-scale-px(5) modular-scale-px(1);
These should be reverted back to the originals.

2021-05-25 19:37 UTC, orjames commented on library/components/button/_button.scss
> +      padding: modular-scale-px(4) modular-scale-px(5) modular-scale-px(1);
ah, yeah good catch

2021-05-27 19:18 UTC, ahmedmodan approved these changes
LGTM. definitely make this a major release since the borders and focus colors are pretty different from the previous design.

2021-05-31 21:31 UTC, merged